name: CD - Deploy - Backend

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: zenwk-org/zenwk-workflows/.github/workflows/zenwk-cd-deploy-docker-template.yml@main
    with:
      service_name: zenwk-security
      environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'test' && 'test' || 'dev' }}
    secrets:
      ORG_REPO_TOKEN: ${{ secrets.ORG_REPO_TOKEN }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
