name: CI - Build - Backend

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - test
      - main
    types: [opened, synchronize, reopened]

  push:
    branches:
      - develop
      - test
      - main
      
permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: zenwk-org/zenwk-workflows/.github/workflows/zenwk-ci-build-docker-template.yml@main
    with:
      service_name: zenwk-security
      image_name: zenwk-org/zenwk-security
      dockerfile_path: zenwk-security/src/main/resources/docker/Dockerfile
      build_context: zenwk-security
      publish_image: ${{ github.event_name == 'push' }}
    secrets:
      GRADLE_PLUGIN_TOKEN: ${{ secrets.GRADLE_PLUGIN_TOKEN }} # paso explícito de secretos